# Generated by Django 2.0.2 on 2018-02-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='avgDanceability',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='song',
            name='songName',
            field=models.CharField(max_length=128),
        ),
    ]
