# Generated by Django 2.0.2 on 2018-03-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankify', '0003_auto_20180303_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='spotifyPlaylistURI',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotifySongURI',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='spotifyUserURI',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
