# Generated by Django 2.0.2 on 2018-03-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankify', '0004_auto_20180305_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='avgDanceability',
            new_name='avg_danceability',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='spotifyPlaylistURI',
            new_name='spotify_playlist_uri',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='songName',
            new_name='song_name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='spotifySongURI',
            new_name='spotify_song_uri',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='spotifyUserURI',
            new_name='spotify_user_uri',
        ),
    ]
