# Generated by Django 2.0.2 on 2018-03-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankify', '0006_userprofile_spotify_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='spotify_username',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
