# Generated by Django 2.0.2 on 2018-03-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankify', '0008_auto_20180307_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='creator_display_name',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
