# Generated by Django 2.0.2 on 2018-03-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankify', '0009_playlist_creator_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='creator_display_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
