# Generated by Django 2.0.2 on 2018-03-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankify', '0010_auto_20180312_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='creator_display_name',
            field=models.CharField(default='none', max_length=128),
        ),
    ]
